@startuml


package Ovladanie {

    class Server {
        +sputstiServer()
        +stopServer()

    }

    class Client {
        
    }
}

enum Smer {
    Hore
    Dole
    Vpravo
    Vlavo
}

class Chodec {
    +int x
    +int y
    +chodec_init()
}

class Simulacia {
    +int pocet_replikacii
    +char* cesta_k_suboru
    +simuluj_k_stredu()
    
}


class Svet {
    +Chodec *chodec
    +int ** pole

    +svet_init(hranica_x, hranica_y)
    +svet_destroy()
    +posun_chodca(Smer smer_posunu)
    +uloz_do_suboru_suboru(char * cesta_k_suboru)
    +naformatuj_svet_na_poslanie()
}

class RozhraniePouzivatela {

}

class Input {

}

class Output {

}

' Spojenia

Svet --> Chodec
RozhraniePouzivatela --> Input
RozhraniePouzivatela --> Output
Client --> RozhraniePouzivatela
Server --> Simulacia
Client --> Server
Server --> Client
Svet --> Smer
Simulacia --> Svet
@enduml